# Site wide configuration

title: Charasty Codes
locale: en_UK
description: A Malaysian Ruby programmer in Tokyo.
logo: site-logo.jpg
search: false
url: http://rastamhadi.github.io

# Jekyll configuration

permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jemoji
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: ['.htaccess']
exclude: ['lib', 'config.rb', 'Capfile', 'config', 'log', 'Rakefile', 'Rakefile.rb', 'tmp', 'less', '*.sublime-project', '*.sublime-workspace', 'test', 'spec', 'Gruntfile.js', 'package.json', 'node_modules', 'Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md', 'vendor']

# Site owner

owner:
  name: Rastam Hadi
  avatar: avatar.jpg
  facebook: rastam.hadi
  github: rastamhadi
  instagram: charasty
  google:
